### ISSUE TITLE
500 Internal Server Error on POST /user/register

### ISSUE THREAD

**Issue by mickeymond** [shawlycode/pitchpal#4]
@shawlycode I am getting the Error below when signing up
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Error</title>
</head>

<body>
    <pre>Internal Server Error</pre>
</body>

</html>
```
I think you should look at the Render Logs to begin with.

**Comment by shawlycode** [comment]
This issue is resolved right

**Comment by mickeymond** [comment]
> This issue is resolved right

@shawlycode Still not resolved.
